using System.Collections.Generic;
using Godot;
using HarmonyLib;
using MegaCrit.Sts2.Core.Entities.Creatures;
using MegaCrit.Sts2.Core.Nodes.Combat;

namespace HelloSpire.HelloSpireCode.Characters;

/// <summary>
/// The render-time palette repaint, applied through spine-godot's material slot
/// (set_normal_material). In COMBAT every character now loads its own rig from spine/&lt;name&gt;/
/// (see CharacterSkeletons) with the palette already baked into the pages, so this postfix
/// skips them; it only still paints a character whose rig folder is missing. RoomSkins and
/// EnergyCounterSkins reuse the same material for the rest site and energy counter, which
/// still borrow the Ironclad's art. The shop swaps to the character's own rig instead (see
/// RoomSkins), so it only falls back to this material when that swap fails.
///
/// The three .gdshader files are GENERATED by the sts2-reskin-pipeline workbench from
/// config/palettes.toml — the same rules that bake the combat pages — so the campfire body and
/// the combat body cannot disagree. Edit the palette there and re-run
/// `tools/package.py &lt;character&gt; --install-hellospire`; never edit the shaders by hand.
/// </summary>
[HarmonyPatch(typeof(Creature), nameof(Creature.CreateVisuals))]
internal static class CharacterSkins
{
    private static readonly Dictionary<string, ShaderMaterial> Cache = new();

    /// <summary>The repaint material for a HelloSpire character, or null for anyone else.</summary>
    internal static ShaderMaterial? MaterialFor(MegaCrit.Sts2.Core.Models.CharacterModel? character)
    {
        var shaderPath = character switch
        {
            Paladin => "res://HelloSpire/shaders/paladin_repaint.gdshader",
            Gunslinger => "res://HelloSpire/shaders/gunslinger_repaint.gdshader",
            Alchemist => "res://HelloSpire/shaders/alchemist_repaint.gdshader",
            _ => null,
        };
        if (shaderPath == null) return null;
        if (!Cache.TryGetValue(shaderPath, out var material))
        {
            if (GD.Load<Shader>(shaderPath) is not { } shader) return null;
            material = new ShaderMaterial { Shader = shader };
            if (character is Paladin)
            {
                if (GD.Load<Texture2D>("res://HelloSpire/images/creature/paladin_weapon_page.png") is { } weapon)
                    material.SetShaderParameter("weapon_page", weapon);
                if (GD.Load<Texture2D>("res://HelloSpire/images/creature/paladin_weapon_shop_page.png") is { } shopWeapon)
                    material.SetShaderParameter("weapon_shop_page", shopWeapon);
            }
            if (character is Alchemist &&
                GD.Load<Texture2D>("res://HelloSpire/images/creature/alchemist_weapon_page.png") is { } potion)
                material.SetShaderParameter("weapon_page", potion);
            Cache[shaderPath] = material;
        }
        return material;
    }

    /// <summary>Hand the repaint to every SpineSprite in a subtree (rest site, shop, combat).</summary>
    internal static void ApplyToSpines(Godot.Node root, ShaderMaterial material)
    {
        if (root.GetClass() == "SpineSprite") root.Call("set_normal_material", material);
        foreach (var child in root.GetChildren())
            ApplyToSpines(child, material);
    }

    [HarmonyPostfix]
    private static void Reskin(Creature __instance, NCreatureVisuals? __result)
    {
        if (__result == null) return;
        // A character with authored spine assets (CharacterSkeletons) renders its own art;
        // palette-remapping it would wreck the authored colors.
        if (CharacterSkeletons.SkeletonFor(__instance.Player?.Character) != null) return;
        if (MaterialFor(__instance.Player?.Character) is not { } material) return;
        var body = __result.GetNodeOrNull<Node2D>("%Visuals");
        if (body == null || body.GetClass() != "SpineSprite") return;
        body.Call("set_normal_material", material);
    }
}
