<#
.SYNOPSIS
    Builds HelloSpire and deploys it into the Slay the Spire 2 mods folder for playtesting.

.DESCRIPTION
    Thin wrapper around the project's existing MSBuild pipeline (HelloSpire.csproj already
    has targets that copy build output into $(ModsPath) automatically). This script just:
      - makes sure Directory.Build.props exists (created from the .example on first run)
      - makes sure the game isn't running and locking HelloSpire.dll
      - runs dotnet build (fast, dll/pdb/json only) or dotnet publish (also exports the
        Godot .pck, so art/UI changes actually show up)

.PARAMETER Quick
    Code-only build (dotnet build). Fast, but does NOT re-export the .pck, so Godot-side
    asset/scene changes won't show up in-game. Good for iterating on C# logic only.

.PARAMETER Release
    Build in Release config instead of the default Debug.

.PARAMETER Force
    Kill a running SlayTheSpire2.exe instead of just warning about it.

.EXAMPLE
    .\tools\build-and-deploy.ps1
    Full publish (dll + pck + json) in Debug, deployed to the game's mods folder.

.EXAMPLE
    .\tools\build-and-deploy.ps1 -Quick
    Fast code-only rebuild, skips the Godot .pck export.
#>
[CmdletBinding()]
param(
    [switch]$Quick,
    [switch]$Release,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
$RepoRoot   = Split-Path -Parent $PSScriptRoot
$ProjectDir = $RepoRoot
$Csproj     = Join-Path $ProjectDir 'HelloSpire.csproj'
$DbProps    = Join-Path $ProjectDir 'Directory.Build.props'
$DbExample  = Join-Path $ProjectDir 'Directory.Build.props.example'
$GodotExe   = 'C:\Users\zerol\Documents\Godot_v4.5.1-stable_mono_win64\Godot_v4.5.1-stable_mono_win64.exe'
$GameDir    = 'D:\SteamLibrary\steamapps\common\Slay the Spire 2'
$ModsDir    = Join-Path $GameDir 'mods\HelloSpire'

function Write-Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "    $msg" -ForegroundColor Green }
function Write-Warn2($msg){ Write-Host "    $msg" -ForegroundColor Yellow }

if (-not (Test-Path $Csproj)) {
    throw "Can't find HelloSpire.csproj under $ProjectDir - is this script still inside the repo's tools\ folder?"
}

# ---------------------------------------------------------------------------
# 1. Directory.Build.props (machine-specific, gitignored) - create if missing
# ---------------------------------------------------------------------------
Write-Step "Checking Directory.Build.props"
if (-not (Test-Path $DbProps)) {
    if (-not (Test-Path $GodotExe)) {
        throw "Expected Godot at '$GodotExe' but it's not there. Edit `$GodotExe at the top of this script, or create Directory.Build.props by hand from Directory.Build.props.example."
    }
    $content = @"
<Project>
    <PropertyGroup>
        <!-- Generated by tools\build-and-deploy.ps1 -->
        <GodotPath>$($GodotExe -replace '\\','/')</GodotPath>
        <Sts2Path>$($GameDir -replace '\\','/')</Sts2Path>
    </PropertyGroup>
</Project>
"@
    Set-Content -Path $DbProps -Value $content -Encoding UTF8
    Write-Ok "Created Directory.Build.props (Godot: $GodotExe)"
} else {
    Write-Ok "Already present"
}

if (-not (Test-Path $GameDir)) {
    throw "Slay the Spire 2 not found at '$GameDir'. Edit `$GameDir at the top of this script if it's moved."
}

# ---------------------------------------------------------------------------
# 2. Make sure the game isn't holding HelloSpire.dll open
# ---------------------------------------------------------------------------
Write-Step "Checking for a running game process"
$proc = Get-Process -Name 'SlayTheSpire2' -ErrorAction SilentlyContinue
if ($proc) {
    if ($Force) {
        Write-Warn2 "SlayTheSpire2.exe is running - stopping it (-Force)"
        $proc | Stop-Process -Force
        Start-Sleep -Seconds 1
    } else {
        throw "SlayTheSpire2.exe is running and will hold HelloSpire.dll open, which fails the copy step. Close the game first, or re-run with -Force to kill it automatically."
    }
} else {
    Write-Ok "Game is not running"
}

# ---------------------------------------------------------------------------
# 3. Build / Publish
# ---------------------------------------------------------------------------
$config = if ($Release) { 'Release' } else { 'Debug' }

if ($Quick) {
    Write-Step "dotnet build ($config) - code only, .pck not re-exported"
    dotnet build $Csproj -c $config
} else {
    Write-Step "dotnet publish ($config) - full deploy: dll + pck + json"
    dotnet publish $Csproj -c $config
}

if ($LASTEXITCODE -ne 0) {
    throw "Build failed (exit code $LASTEXITCODE). See output above."
}

# ---------------------------------------------------------------------------
# 4. Report
# ---------------------------------------------------------------------------
Write-Step "Done"
if (Test-Path $ModsDir) {
    Write-Ok "Deployed to: $ModsDir"
    Get-ChildItem $ModsDir | ForEach-Object { Write-Host "      $($_.Name)" -ForegroundColor DarkGray }
} else {
    Write-Warn2 "Build succeeded but $ModsDir wasn't found - check the csproj's CopyToModsFolderOnBuild/GodotPublish targets."
}
Write-Host ""
Write-Host "Launch the game with 'Play with Mods', enable HelloSpire in the Mods menu (restart once if it's newly enabled)." -ForegroundColor White
